services:
  shrinkerr:
    image: shrinkerr:latest
    container_name: shrinkerr
    ports:
      - "6680:6680"
    volumes:
      - /home/hal9000/shrinkerr/data:/app/data
      - type: bind
        source: /home/hal9000/HALHUB
        target: /media
        bind:
          propagation: rslave
      - /home/hal9000/Downloads/completed/TV:/downloads/tv:rw
      - /home/hal9000/Downloads/completed/Movies:/downloads/movies:rw
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SQUEEZARR_DB_PATH=/app/data/squeezarr.db
      - SQUEEZARR_MEDIA_ROOT=/media
      - PGID=1000
      - PUID=1000
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]
