// ISO 639-2/B codes + English names for the manual track-language picker
// (v0.9.43). Curated common set — enough to cover typical libraries without a
// 500-entry dropdown. Codes match what mkvpropedit / ffmpeg write.
// v0.9.47: exported sorted alphabetically by name (see bottom).
const _LANGUAGES: { code: string; name: string }[] = [
  { code: "eng", name: "English" },
  { code: "spa", name: "Spanish" },
  { code: "fre", name: "French" },
  { code: "ger", name: "German" },
  { code: "ita", name: "Italian" },
  { code: "por", name: "Portuguese" },
  { code: "dut", name: "Dutch" },
  { code: "rus", name: "Russian" },
  { code: "pol", name: "Polish" },
  { code: "swe", name: "Swedish" },
  { code: "nor", name: "Norwegian" },
  { code: "dan", name: "Danish" },
  { code: "fin", name: "Finnish" },
  { code: "ice", name: "Icelandic" },
  { code: "cze", name: "Czech" },
  { code: "slo", name: "Slovak" },
  { code: "hun", name: "Hungarian" },
  { code: "rum", name: "Romanian" },
  { code: "gre", name: "Greek" },
  { code: "tur", name: "Turkish" },
  { code: "ukr", name: "Ukrainian" },
  { code: "bul", name: "Bulgarian" },
  { code: "hrv", name: "Croatian" },
  { code: "srp", name: "Serbian" },
  { code: "slv", name: "Slovenian" },
  { code: "cat", name: "Catalan" },
  { code: "gle", name: "Irish" },
  { code: "wel", name: "Welsh" },
  { code: "jpn", name: "Japanese" },
  { code: "chi", name: "Chinese" },
  { code: "kor", name: "Korean" },
  { code: "hin", name: "Hindi" },
  { code: "ara", name: "Arabic" },
  { code: "heb", name: "Hebrew" },
  { code: "tha", name: "Thai" },
  { code: "vie", name: "Vietnamese" },
  { code: "ind", name: "Indonesian" },
  { code: "may", name: "Malay" },
  { code: "tgl", name: "Tagalog" },
  { code: "per", name: "Persian" },
  { code: "ben", name: "Bengali" },
  { code: "tam", name: "Tamil" },
  { code: "tel", name: "Telugu" },
  { code: "urd", name: "Urdu" },
  { code: "afr", name: "Afrikaans" },
  { code: "est", name: "Estonian" },
  { code: "lav", name: "Latvian" },
  { code: "lit", name: "Lithuanian" },
  { code: "mul", name: "Multiple languages" },
  { code: "und", name: "Undetermined" },
];

export const LANGUAGES = [..._LANGUAGES].sort((a, b) => a.name.localeCompare(b.name));
